spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sip_cotizaciones?useSSL=false # conexion a la base
    username: root
    password: 74163991
#    driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.testWhileIdle = true
#spring.datasource.validationQuery = SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true 
  http:
    converters:
      preferred-json-mapper: jackson # Preferred JSON mapper to use for HTTP message conversion. Set to "gson" to force the use of Gson when both it and Jackson are on the classpath.
  mail:
    default-encoding: UTF-8 # Default MimeMessage encoding.
    host: smtp.gmail.com # SMTP server host. For instance `smtp.example.com`
    password: unimer873432bot # Login password of the SMTP server.
    port: 587 # SMTP server port.
    protocol: smtp # Protocol used by the SMTP server.
    test-connection: false # Test that the mail server is available on startup.
    username: bot@unimercentroamerica.info # Login user of the SMTP server. 
# Naming strategy
#spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
 
# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager)
 
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

  mandatory-file-encoding: UTF-8  # Expected character encoding the application must use.
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  thymeleaf:
    cache: false
banner:
  charset: UTF-8 # Banner file encoding.
  location: classpath:/static/public/banner.txt
server:
  display-name: cotizaciones # Display name of the application.
  error:
    path: /error # Path of the error controller.
    whitelabel:
      enabled: true
  port: 8090